language: ruby
cache: bundler

sudo: required
dist: trusty

group: edge

addons:
  apt:
    sources:
    - chef-current-trusty
    packages:
    - chefdk

matrix:
  include:
  - os: osx
    ENV: BREWFILE=Brewfile
    osx_image: xcode9.2
  - os: osx
    ENV: BREWFILE=Brewfile2
    osx_image: xcode9.2

services: docker

script:
- travis_retry brew bundle --file=$BREWFILE
