# Don't edit, this.  Edit list.yml and run ./main.py to generate this.

language: ruby
cache: bundler
sudo: required
dist: trusty
group: edge
os: osx
osx_image: xcode10.2
env:
- PLAYBOOK=playbook_macos1.yml
- PLAYBOOK=playbook_macos2.yml
- PLAYBOOK=playbook_macos3.yml
- PLAYBOOK=playbook_macos4.yml
- PLAYBOOK=playbook_macos5.yml
- PLAYBOOK=playbook_macos6.yml
- PLAYBOOK=playbook_macos7.yml
- PLAYBOOK=playbook_macos8.yml
- PLAYBOOK=playbook_macos9.yml
- PLAYBOOK=playbook_macos10.yml
- PLAYBOOK=playbook_macos11.yml
- PLAYBOOK=playbook_macos12.yml
- PLAYBOOK=playbook_macos13.yml
- PLAYBOOK=playbook_macos14.yml
- PLAYBOOK=playbook_macos15.yml
- PLAYBOOK=playbook_macos16.yml
- PLAYBOOK=playbook_macos17.yml
- PLAYBOOK=playbook_macos18.yml
- PLAYBOOK=playbook_macos19.yml
- PLAYBOOK=playbook_macos20.yml
- PLAYBOOK=playbook_macos21.yml
- PLAYBOOK=playbook_macos22.yml
- PLAYBOOK=playbook_macos23.yml
- PLAYBOOK=playbook_macos24.yml
- PLAYBOOK=playbook_macos25.yml
- PLAYBOOK=playbook_macos26.yml
- PLAYBOOK=playbook_macos27.yml
script:
- travis_retry ansible-playbook --verbose --verbose $PLAYBOOK