language: ruby
cache: bundler

sudo: required
dist: trusty

group: edge

addons:
  apt:
    sources:
    - chef-current-trusty
    packages:
    - chefdk

matrix:
  include:
  - os: osx
    osx_image: xcode9.2

services: docker

script:
- travis_wait 50 brew bundle --verbose --verbose
