[brews]
'ack' = 'yes'
'apr' = 'yes'
'apr-util' = 'yes'
'aspell' = 'yes'
'augeas' = 'yes'
'autoconf' = 'yes'
'automake' = 'yes'
'autossh' = 'yes'
'aws-cfn-tools' = 'yes'
'aws-elasticache' = 'yes'
'aws-sam-cli' = 'yes'
'awscli' = 'yes'
'bash' = 'yes'
'bash-completion@2' = 'yes'
'bats' = 'yes'
'bazaar' = 'yes'
'bazel' = 'yes'
'bdw-gc' = 'yes'
'blackbox' = 'yes'
'bower' = 'yes'
'brew-graph' = 'yes'
'bsdiff' = 'yes'
'buildkit' = 'yes'
'c-ares' = 'yes'
'cairomm' = 'yes'
'cassandra' = 'yes'
'certbot' = 'yes'
'cfssl' = 'yes'
'chrome-cli' = 'yes'
'clasp' = 'yes'
'cliclick' = 'yes'
'cloud-watch' = 'yes'
'cmake' = 'yes'
'consul' = 'yes'
'consul-template' = 'yes'
'coreutils' = 'yes'
'corkscrew' = 'yes'
'csvkit' = 'yes'
'ctags' = 'yes'
'cunit' = 'yes'
'curl' = 'yes'
'dateutils' = 'yes'
'delta' = 'yes'
'dialog' = 'yes'
'dnsmasq' = 'yes'
'docker-completion' = 'yes'
'docker-compose' = 'yes'
'docker-compose-completion' = 'yes'
'docker-machine' = 'yes'
'docker-machine-completion' = 'yes'
'docker-machine-driver-xhyve' = 'yes'
'dockerize' = 'yes'
'dos2unix' = 'yes'
'duck' = 'yes'
'dvm' = 'yes'
'ec2-ami-tools' = 'yes'
'editorconfig' = 'yes'
'elasticsearch' = 'yes'
'elinks' = 'yes'
'emacs' = 'yes'
'enscript' = 'yes'
'entr' = 'yes'
'envconsul' = 'yes'
'etcd' = 'yes'
'exa' = 'yes'
'faad2' = 'yes'
'ffsend' = 'yes'
'findutils' = 'yes'
'fontconfig' = 'yes'
'fping' = 'yes'
'fswatch' = 'yes'
'fzf' = 'yes'
'gawk' = 'yes'
'gdk-pixbuf' = 'yes'
'geckodriver' = 'yes'
'geoip' = 'yes'
'ghc' = 'yes'
'gist' = 'yes'
'git' = 'yes'
'git-extras' = 'yes'
'git-fixup' = 'yes'
'git-lfs' = 'yes'
'git-when-merged' = 'yes'
'gitversion' = 'yes'
'glooctl' = 'yes'
'gnu-getopt' = 'yes'
'gnu-indent' = 'yes'
'gnu-sed' = 'yes'
'gnu-tar' = 'yes'
'gnu-which' = 'yes'
'gnupg' = 'yes'
'gobject-introspection' = 'yes'
'golang' = 'yes'
'gradle' = 'yes'
'graphviz' = 'yes'
'grep' = 'yes'
'groovy' = 'yes'
'gsl' = 'yes'
'guile' = 'yes'
'hadolint' = 'yes'
'helmfile' = 'yes'
'highlight' = 'yes'
'htop-osx' = 'yes'
'httpie' = 'yes'
'hub' = 'yes'
'hugo' = 'yes'
'icu4c' = 'yes'
'ilmbase' = 'yes'
'imagemagick' = 'yes'
'intltool' = 'yes'
'iperf3' = 'yes'
'irssi' = 'yes'
'istioctl' = 'yes'
'jid' = 'yes'
'jpeg' = 'yes'
'jq' = 'yes'
'jsonpp' = 'yes'
'kqwait' = 'yes'
'kubernetes-cli' = 'yes'
'kubernetes-helm' = 'yes'
'lame' = 'yes'
'ledger' = 'yes'
'logrotate' = 'yes'
'logstash' = 'yes'
'lsof' = 'yes'
'lua' = 'yes'
'luajit' = 'yes'
'luarocks' = 'yes'
'lynx' = 'yes'
'make' = 'yes'
'makedepend' = 'yes'
'maven' = 'yes'
'metricbeat' = 'yes'
'mitmproxy' = 'yes'
'mmv' = 'yes'
'mobile-shell' = 'yes'
'mono' = 'yes'
'mosh' = 'yes'
'msgpack' = 'yes'
'msmtp' = 'yes'
'mtr' = 'yes'
'mutt' = 'yes'
'mvnvm' = 'yes'
'n' = 'yes'
'ncdu' = 'yes'
'neovim' = 'yes'
'nghttp2' = 'yes'
'nginx' = 'yes'
'nmap' = 'yes'
'node' = 'yes'
'nvm' = 'yes'
'oniguruma' = 'yes'
'opam' = 'yes'
'openexr' = 'yes'
'openvpn' = 'yes'
'p7zip' = 'yes'
'packer' = 'yes'
'pango' = 'yes'
'pangomm' = 'yes'
'parallel' = 'yes'
'patchutils' = 'yes'
'pidof' = 'yes'
'pinentry' = 'yes'
'pixman' = 'yes'
'protobuf' = 'yes'
'prototool' = 'yes'
'psgrep' = 'yes'
'pssh' = 'yes'
'pyenv' = 'yes'
'pyenv-virtualenv' = 'yes'
'pyenv-virtualenvwrapper' = 'yes'
'python' = 'yes'
'python3' = 'yes'
'qemu' = 'yes'
'r' = 'yes'
'ranger' = 'yes'
'rbenv' = 'yes'
'rdesktop' = 'yes'
're2c' = 'yes'
'reattach-to-user-namespace' = 'yes'
'recode' = 'yes'
'redo' = 'yes'
'restic' = 'yes'
'ripgrep' = 'yes'
'rpm2cpio' = 'yes'
'rsync' = 'yes'
'ruby-build' = 'yes'
'rust' = 'yes'
's-lang' = 'yes'
'selenium-server-standalone' = 'yes'
'shfmt' = 'yes'
'socat' = 'yes'
'spdylay' = 'yes'
'speedtest-cli' = 'yes'
'sphinx-doc' = 'yes'
'squid' = 'yes'
'ssh-copy-id' = 'yes'
'sshuttle' = 'yes'
'stow' = 'yes'
'subversion' = 'yes'
'terminal-notifier' = 'yes'
'terraform' = 'yes'
'terraforming' = 'yes'
'tesseract' = 'yes'
'texi2html' = 'yes'
'texinfo' = 'yes'
'the_platinum_searcher' = 'yes'
'the_silver_searcher' = 'yes'
'tidy-html5' = 'yes'
'tig' = 'yes'
'timewarrior' = 'yes'
'tmux' = 'yes'
'tokyo-cabinet' = 'yes'
'travis' = 'yes'
'tree' = 'yes'
'uni2ascii' = 'yes'
'unibilium' = 'yes'
'unixodbc' = 'yes'
'vault' = 'yes'
'vifm' = 'yes'
'vim' = 'yes'
'watch' = 'yes'
'watchman' = 'yes'
'wdiff' = 'yes'
'websocat' = 'yes'
'wget' = 'yes'
'wiggle' = 'yes'
'wireshark' = 'yes'
'wsk' = 'yes'
'x264' = 'yes'
'xhyve' = 'yes'
'xml-coreutils' = 'yes'
'xmlstarlet' = 'yes'
'xvid' = 'yes'
'xz' = 'yes'
'yajl' = 'yes'
'yarn' = 'yes'
'z' = 'yes'
[casks]
'alfred' = 'yes'
'amethyst' = 'yes'
'blender' = 'yes'
'caskroom/versions/java8' = 'yes'
'charles' = 'yes'
'chromedriver' = 'yes'
'cyberduck' = 'yes'
'disk-inventory-x' = 'yes'
'docker' = 'yes'
'dotnet-sdk' = 'yes'
'drawio' = 'yes'
'dropbox' = 'yes'
'eclipse-ide' = 'yes'
'firefox' = 'yes'
'gitter' = 'yes'
'google-chrome' = 'yes'
'google-cloud-sdk' = 'yes'
'hammerspoon' = 'yes'
'iterm2' = 'yes'
'keybase' = 'yes'
'kindle' = 'yes'
'kitematic' = 'yes'
'macpass' = 'yes'
'maxtex' = 'yes'
'minikube' = 'yes'
'mongodb' = 'yes'
'mysql-shell' = 'yes'
'mysqlworkbench' = 'yes'
'neo4j' = 'yes'
'obs' = 'yes'
'opera' = 'yes'
'paste' = 'yes'
'postman' = 'yes'
'powershell' = 'yes'
'screenflick' = 'yes'
'skype' = 'yes'
'slack' = 'yes'
'spectacle' = 'yes'
'the-unarchiver' = 'yes'
'tunnelblick' = 'yes'
'vagrant' = 'yes'
'virtualbox' = 'yes'
'virtualbox-extension-pack' = 'yes'
'visual-studio-code' = 'yes'
'vlc' = 'yes'
'wireshark' = 'yes'
'xquartz' = 'yes'
[mass]
'Microsoft Remote Desktop, id: 1295203466' = 'yes'
'Xcode, id: 497799835' = 'yes'
[taps]
'aws/tap' = 'yes'
'azure/draft' = 'yes'
'caskroom/cask' = 'yes'
'domt4/autoupdate' = 'yes'
'facebook/fb' = 'yes'
'habitat-sh/habitat' = 'yes'
'homebrew/bundle' = 'yes'
'homebrew/cask' = 'yes'
'homebrew/core' = 'yes'
'homebrew/services' = 'yes'
'ksonnet/tap' = 'yes'
'martido/brew-graph' = 'yes'
'mas-cli/tap' = 'yes'
'neovim/neovim' = 'yes'
'weaveworks/tap' = 'yes'
