# Don't edit, this.  Edit list.yml and run ./main.py to generate this.
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
# FIXME: dictionary
#   - name: Install mas's
#     homebrew_mas:
#       name: {'Microsoft Remote Desktop': None, 'id': 1295203466},{'Xcode': None, 'id': 497799835}
  - name: Install tap(s)
    homebrew_tap:
      name: aws/tap,azure/draft,caskroom/cask,domt4/autoupdate,facebook/fb,habitat-sh/habitat,homebrew/bundle,homebrew/cask,homebrew/core,homebrew/services,ksonnet/tap,martido/brew-graph,neovim/neovim,weaveworks/tap
      state: present
  - name: Install brews
    homebrew:
      name: emacs,enscript,entr,envconsul,etcd,exa,exact-image,exim,faad2,fades,ffe,ffsend,findutils,fluxctl,fontconfig,fping,fswatch,fzf,gawk,gdk-pixbuf,geckodriver,geoip,ghc,gist,git,git-extras,git-fixup,git-lfs,git-when-merged,gitversion
      state: present